# Generated by Django 3.2 on 2021-04-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='num_of_pages',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
