# Generated by Django 3.2 on 2021-04-28 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_book_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.TextField(help_text='Podaj krótki opis książki.', max_length=1000),
        ),
    ]
